"""
@Author: Farzana Shaikh
@Date: 18-01-2022 04:00PM
@Last Modified by: Farzana Shaikh
@Last Modified time: 18-01-2022 04:00PM
@Title : NumPy Problems
"""

In [63]:
%run 'Logger.py'
# Importing Logger Object from Logger.py


1. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.

In [48]:
import numpy as np
import logging
logging.basicConfig(level=logging.DEBUG)


def list_to_array():
    """
       Description:
          Function is used to convert list to array.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    list1 = [12.23, 13.32, 100, 36.32]
    logging.debug("Original List:{}".format(list1))
   #  np.array() is used to create an array.
    new_array = np.array(list1)
    logging.debug("One-dimensional NumPy array: {}".format(new_array) )


if __name__ == "__main__":
    list_to_array()


DEBUG:root:Original List:[12.23, 13.32, 100, 36.32]
DEBUG:root:One-dimensional NumPy array: [ 12.23  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10.

In [49]:
import numpy as np
import logging
logging.basicConfig(level=logging.DEBUG)


def matrix_with_range():
    """
       Description:
          Function is used to create array matrix of given condition.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
   #  arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval.
   # The numpy.reshape() function shapes an array without changing the data of the array.
    new_array =  np.arange(2, 11).reshape(3,3)
    logging.debug("The array with given range is {}".format(new_array))


if __name__ == "__main__":
    matrix_with_range()

DEBUG:root:The array with given range is [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [50]:

import numpy as np
import logging
logging.basicConfig(level=logging.DEBUG)


def null_vector_specific_value_update():
    """
       Description:
          Function is used to create array with null vectors and update it with specific value at specific index.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
   #  The numpy.zeros() function returns a new array of given shape and type, with zeros.
    new_array = np.zeros(10)
    logging.debug("The array with given condition is {}".format(new_array))
    logging.debug("Update sixth value to 11")
    new_array[6] = 11
    logging.debug("The array with given condition is {}".format(new_array))


if __name__ == "__main__":
    null_vector_specific_value_update()

DEBUG:root:The array with given condition is [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
DEBUG:root:Update sixth value to 11
DEBUG:root:The array with given condition is [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).

In [51]:

import numpy as np
import logging
logging.basicConfig(level=logging.DEBUG)


def reverse_array():
    """
       Description:
          Function is used to reverse an array.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    new_array = np.arange(12, 38)
    logging.debug("The Original array is {}".format(new_array))
   #  array slicing
    reversed_array = new_array[::-1]
    logging.debug("Reversed Array is {}".format(reversed_array))


if __name__ == "__main__":
    reverse_array()

DEBUG:root:The Original array is [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
DEBUG:root:Reversed Array is [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.

In [52]:
import numpy as np
import logging
logging.basicConfig(level=logging.DEBUG)


def array_two_dimentional():
    """
       Description:
          Function is used to create two dimentional array with border of specific digit.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
   #  The numpy.ones() function returns a new array of given shape and type, with ones.
    new_array = np.ones((5, 5))
    logging.debug("The Original array is {}".format(new_array))
    new_array[1:-1, 1:-1] = 0
    logging.debug("1 on the border and 0 inside in the array \n{}".format(new_array))


if __name__ == "__main__":
    array_two_dimentional()

DEBUG:root:The Original array is [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
DEBUG:root:1 on the border and 0 inside in the array 
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.

In [53]:
import numpy as np
import logging
logging.basicConfig(level=logging.DEBUG)

def to_add_zeroes_in_an_array():
    """
       Description:
          Function is used to create matrix with zeroes at the border.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    new_array = np.ones((3,3))
    logging.debug("Original array: \n {}".format(new_array))
   #  numpy.pad() function is used to pad the Numpy arrays. 
    new_array = np.pad(new_array, pad_width=1, mode='constant', constant_values=0)
    logging.debug("0 on the border and 1 inside in the array:\n {}".format(new_array))

if __name__ == "__main__":
    to_add_zeroes_in_an_array()

DEBUG:root:Original array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
DEBUG:root:0 on the border and 1 inside in the array:
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [54]:
import numpy as np
import logging
logging.basicConfig(level=logging.DEBUG)

def checkerboard_pattern():
    """
       Description:
          Function is used to create matrix of checkerboard pattern.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    new_array = np.zeros((8,8),dtype=int)
    new_array[1::2,::2] = 1
    new_array[::2,1::2] = 1
    logging.debug("Checkerboard pattern:\n {}".format(new_array))
   

if __name__ == "__main__":
    checkerboard_pattern()


DEBUG:root:Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


8. Write a Python program to convert a list and tuple into arrays.

In [55]:
import numpy as np
import logging
logging.basicConfig(level=logging.DEBUG)

def list_to_array():
    """
       Description:
          Function is used to convert list to array.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    new_list = [1, 2, 3, 4, 5, 6, 7, 8,"Hello", "Universe"]
   #  numpy.asarray()function is used when we want to convert input to an array.
    logging.debug("List to array: \n {}".format(np.asarray(new_list)))

def tuple_to_array():
    """
       Description:
          Function is used to convert tuple to array.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    new_tuple = ([8, 4, 6], [1, 2, 3])
    logging.debug("Tuple to array:\n {}".format(np.asarray(new_tuple)))


if __name__ == "__main__":
    list_to_array()
    tuple_to_array()

DEBUG:root:List to array: 
 ['1' '2' '3' '4' '5' '6' '7' '8' 'Hello' 'Universe']
DEBUG:root:Tuple to array:
 [[8 4 6]
 [1 2 3]]


9. Write a Python program to append values to the end of an array.

In [56]:
import numpy as np
import logging
logging.basicConfig(level=logging.DEBUG)

def append_elements_to_array():
    """
       Description:
          Function is used to append elements to array.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    new_array = [10, 20, 30]
    logging.debug("Original array: \n {}".format(new_array))
   #  The numpy.append() appends values along the mentioned axis at the end of the array
    new_array = np.append(new_array, [[40, 50, 60], [70, 80, 90]])
    logging.debug("After append values to the end of the array:\n {}".format(new_array))


if __name__ == "__main__":
    append_elements_to_array()

DEBUG:root:Original array: 
 [10, 20, 30]
DEBUG:root:After append values to the end of the array:
 [10 20 30 40 50 60 70 80 90]


10. Write a Python program to find the real and imaginary parts of an array of complex numbers.

In [57]:
import logging
logging.basicConfig(level=logging.DEBUG)
import numpy as np

def to_find_real_and_imaginary_part_of_an_array():
    """
       Description:
          Function is used to get real and imaginary part of the equation.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    x_array = np.sqrt([1+0j])
    y_array = np.sqrt([0+1j])

    logging.debug("Original x_array: \n {}".format(x_array))
    logging.debug("Original y_array: \n {}".format(y_array))
    logging.debug("Real part of the x_array:\n {}".format(x_array.real))
    logging.debug("Real part of the y_array:\n {}".format(y_array.real))
    logging.debug("Imaginary part of the X_array:\n {}".format(x_array.imag))
    logging.debug("Imaginary part of the y_array:\n {}".format(y_array.imag))

if __name__ == "__main__":
    to_find_real_and_imaginary_part_of_an_array()


DEBUG:root:Original x_array: 
 [1.+0.j]
DEBUG:root:Original y_array: 
 [0.70710678+0.70710678j]
DEBUG:root:Real part of the x_array:
 [1.]
DEBUG:root:Real part of the y_array:
 [0.70710678]
DEBUG:root:Imaginary part of the X_array:
 [0.]
DEBUG:root:Imaginary part of the y_array:
 [0.70710678]


11. Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [66]:
from Logger import logger
import numpy as np
def to_find_length_size_bytes_of_an_array():
    new_array = np.array([1,2,3], dtype=np.float64)
    logger.debug("Size of the an array:{} ".format(new_array.size))
    logger.debug("Length of one array element in bytes: {} ".format(new_array.itemsize))
    logger.debug("Total bytes consumed by the elements of the an array: {} ".format(new_array.nbytes))

if __name__ == "__main__":
    to_find_length_size_bytes_of_an_array()

2022-01-18 20:21:28,145:Logger:Size of the an array:3 
DEBUG:Logger:Size of the an array:3 
2022-01-18 20:21:28,149:Logger:Length of one array element in bytes: 8 
DEBUG:Logger:Length of one array element in bytes: 8 
2022-01-18 20:21:28,152:Logger:Total bytes consumed by the elements of the an array: 24 
DEBUG:Logger:Total bytes consumed by the elements of the an array: 24 
