"""
@Author: Farzana Shaikh
@Date: 18-01-2022 04:00PM
@Last Modified by: Farzana Shaikh
@Last Modified time: 18-01-2022 04:00PM
@Title : NumPy Problems
"""

In [63]:
%run 'Logger.py'
# Importing Logger Object from Logger.py


1. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.

In [48]:
import numpy as np
import logging
logging.basicConfig(level=logging.DEBUG)


def list_to_array():
    """
       Description:
          Function is used to convert list to array.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    list1 = [12.23, 13.32, 100, 36.32]
    logging.debug("Original List:{}".format(list1))
   #  np.array() is used to create an array.
    new_array = np.array(list1)
    logging.debug("One-dimensional NumPy array: {}".format(new_array) )


if __name__ == "__main__":
    list_to_array()


DEBUG:root:Original List:[12.23, 13.32, 100, 36.32]
DEBUG:root:One-dimensional NumPy array: [ 12.23  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10.

In [49]:
import numpy as np
import logging
logging.basicConfig(level=logging.DEBUG)


def matrix_with_range():
    """
       Description:
          Function is used to create array matrix of given condition.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
   #  arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval.
   # The numpy.reshape() function shapes an array without changing the data of the array.
    new_array =  np.arange(2, 11).reshape(3,3)
    logging.debug("The array with given range is {}".format(new_array))


if __name__ == "__main__":
    matrix_with_range()

DEBUG:root:The array with given range is [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [50]:

import numpy as np
import logging
logging.basicConfig(level=logging.DEBUG)


def null_vector_specific_value_update():
    """
       Description:
          Function is used to create array with null vectors and update it with specific value at specific index.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
   #  The numpy.zeros() function returns a new array of given shape and type, with zeros.
    new_array = np.zeros(10)
    logging.debug("The array with given condition is {}".format(new_array))
    logging.debug("Update sixth value to 11")
    new_array[6] = 11
    logging.debug("The array with given condition is {}".format(new_array))


if __name__ == "__main__":
    null_vector_specific_value_update()

DEBUG:root:The array with given condition is [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
DEBUG:root:Update sixth value to 11
DEBUG:root:The array with given condition is [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).

In [51]:

import numpy as np
import logging
logging.basicConfig(level=logging.DEBUG)


def reverse_array():
    """
       Description:
          Function is used to reverse an array.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    new_array = np.arange(12, 38)
    logging.debug("The Original array is {}".format(new_array))
   #  array slicing
    reversed_array = new_array[::-1]
    logging.debug("Reversed Array is {}".format(reversed_array))


if __name__ == "__main__":
    reverse_array()

DEBUG:root:The Original array is [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
DEBUG:root:Reversed Array is [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.

In [52]:
import numpy as np
import logging
logging.basicConfig(level=logging.DEBUG)


def array_two_dimentional():
    """
       Description:
          Function is used to create two dimentional array with border of specific digit.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
   #  The numpy.ones() function returns a new array of given shape and type, with ones.
    new_array = np.ones((5, 5))
    logging.debug("The Original array is {}".format(new_array))
    new_array[1:-1, 1:-1] = 0
    logging.debug("1 on the border and 0 inside in the array \n{}".format(new_array))


if __name__ == "__main__":
    array_two_dimentional()

DEBUG:root:The Original array is [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
DEBUG:root:1 on the border and 0 inside in the array 
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.

In [53]:
import numpy as np
import logging
logging.basicConfig(level=logging.DEBUG)

def to_add_zeroes_in_an_array():
    """
       Description:
          Function is used to create matrix with zeroes at the border.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    new_array = np.ones((3,3))
    logging.debug("Original array: \n {}".format(new_array))
   #  numpy.pad() function is used to pad the Numpy arrays. 
    new_array = np.pad(new_array, pad_width=1, mode='constant', constant_values=0)
    logging.debug("0 on the border and 1 inside in the array:\n {}".format(new_array))

if __name__ == "__main__":
    to_add_zeroes_in_an_array()

DEBUG:root:Original array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
DEBUG:root:0 on the border and 1 inside in the array:
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [54]:
import numpy as np
import logging
logging.basicConfig(level=logging.DEBUG)

def checkerboard_pattern():
    """
       Description:
          Function is used to create matrix of checkerboard pattern.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    new_array = np.zeros((8,8),dtype=int)
    new_array[1::2,::2] = 1
    new_array[::2,1::2] = 1
    logging.debug("Checkerboard pattern:\n {}".format(new_array))
   

if __name__ == "__main__":
    checkerboard_pattern()


DEBUG:root:Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


8. Write a Python program to convert a list and tuple into arrays.

In [55]:
import numpy as np
import logging
logging.basicConfig(level=logging.DEBUG)

def list_to_array():
    """
       Description:
          Function is used to convert list to array.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    new_list = [1, 2, 3, 4, 5, 6, 7, 8,"Hello", "Universe"]
   #  numpy.asarray()function is used when we want to convert input to an array.
    logging.debug("List to array: \n {}".format(np.asarray(new_list)))

def tuple_to_array():
    """
       Description:
          Function is used to convert tuple to array.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    new_tuple = ([8, 4, 6], [1, 2, 3])
    logging.debug("Tuple to array:\n {}".format(np.asarray(new_tuple)))


if __name__ == "__main__":
    list_to_array()
    tuple_to_array()

DEBUG:root:List to array: 
 ['1' '2' '3' '4' '5' '6' '7' '8' 'Hello' 'Universe']
DEBUG:root:Tuple to array:
 [[8 4 6]
 [1 2 3]]


9. Write a Python program to append values to the end of an array.

In [56]:
import numpy as np
import logging
logging.basicConfig(level=logging.DEBUG)

def append_elements_to_array():
    """
       Description:
          Function is used to append elements to array.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    new_array = [10, 20, 30]
    logging.debug("Original array: \n {}".format(new_array))
   #  The numpy.append() appends values along the mentioned axis at the end of the array
    new_array = np.append(new_array, [[40, 50, 60], [70, 80, 90]])
    logging.debug("After append values to the end of the array:\n {}".format(new_array))


if __name__ == "__main__":
    append_elements_to_array()

DEBUG:root:Original array: 
 [10, 20, 30]
DEBUG:root:After append values to the end of the array:
 [10 20 30 40 50 60 70 80 90]


10. Write a Python program to find the real and imaginary parts of an array of complex numbers.

In [57]:
import logging
logging.basicConfig(level=logging.DEBUG)
import numpy as np

def to_find_real_and_imaginary_part_of_an_array():
    """
       Description:
          Function is used to get real and imaginary part of the equation.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    x_array = np.sqrt([1+0j])
    y_array = np.sqrt([0+1j])

    logging.debug("Original x_array: \n {}".format(x_array))
    logging.debug("Original y_array: \n {}".format(y_array))
    logging.debug("Real part of the x_array:\n {}".format(x_array.real))
    logging.debug("Real part of the y_array:\n {}".format(y_array.real))
    logging.debug("Imaginary part of the X_array:\n {}".format(x_array.imag))
    logging.debug("Imaginary part of the y_array:\n {}".format(y_array.imag))

if __name__ == "__main__":
    to_find_real_and_imaginary_part_of_an_array()


DEBUG:root:Original x_array: 
 [1.+0.j]
DEBUG:root:Original y_array: 
 [0.70710678+0.70710678j]
DEBUG:root:Real part of the x_array:
 [1.]
DEBUG:root:Real part of the y_array:
 [0.70710678]
DEBUG:root:Imaginary part of the X_array:
 [0.]
DEBUG:root:Imaginary part of the y_array:
 [0.70710678]


11. Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.

In [66]:
from Logger import logger
import numpy as np

def to_find_length_size_bytes_of_an_array():
    """
       Description:
          Function is used to find the length,size and bytes of an array.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    new_array = np.array([1,2,3], dtype=np.float64)
    logger.debug("Size of the an array:{} ".format(new_array.size))
    logger.debug("Length of one array element in bytes: {} ".format(new_array.itemsize))
    logger.debug("Total bytes consumed by the elements of the an array: {} ".format(new_array.nbytes))

if __name__ == "__main__":
    to_find_length_size_bytes_of_an_array()

2022-01-18 20:21:28,145:Logger:Size of the an array:3 
DEBUG:Logger:Size of the an array:3 
2022-01-18 20:21:28,149:Logger:Length of one array element in bytes: 8 
DEBUG:Logger:Length of one array element in bytes: 8 
2022-01-18 20:21:28,152:Logger:Total bytes consumed by the elements of the an array: 24 
DEBUG:Logger:Total bytes consumed by the elements of the an array: 24 


12. Write a Python program to find common values between two arrays.

In [2]:
from Logger import logger
import numpy as np

def to_find_common_values_between_two_arrays():
    """
       Description:
          Function is used to find common elements between two arrays.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    array1 = np.array([0, 10, 20, 40, 60])
    logger.debug("Array1:\n {}".format(array1))
    array2 = [10, 30, 40]
    logger.debug("Array2:\n {}".format(array2))
    # numpy.intersect1d() function find the intersection of two arrays and return the sorted, unique values that are in both of the input arrays.
    logger.debug("Common values between two arrays:\n {}".format(np.intersect1d(array1, array2)))

if __name__ == "__main__":
    to_find_common_values_between_two_arrays()

2022-01-19 00:57:57,606:Logger:Array1:
 [ 0 10 20 40 60]
2022-01-19 00:57:57,608:Logger:Array2:
 [10, 30, 40]
2022-01-19 00:57:57,610:Logger:Common values between two arrays:
 [10 40]


13. Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.

In [2]:
from Logger import logger
import numpy as np

def to_find_difference_between_two_arrays():
    """
       Description:
          Function is used to find difference between two arrays.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    array1 = np.array([0, 10, 20, 40, 60, 80])
    logger.debug("Array1: {}".format(array1))
    array2 = [10, 30, 40, 50, 70]
    logger.debug("Array2: {}".format(array2))
    # numpy.setdiff1d() function find the set difference of two arrays and return the unique values in arr1 that are not in arr2.
    logger.debug("Unique values in Array1 that are not in Array2:{}".format(np.setdiff1d(array1, array2)))

if __name__ == "__main__":
    to_find_difference_between_two_arrays()
    


2022-01-19 01:09:50,979:Logger:Array1: [ 0 10 20 40 60 80]
2022-01-19 01:09:50,982:Logger:Array2: [10, 30, 40, 50, 70]
2022-01-19 01:09:50,983:Logger:Unique values in array1 that are not in array2:[ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.

In [1]:
from Logger import logger
import numpy as np

def to_find_set_exclusive_or_of_two_arrays():
    """
       Description:
          Function is used to find set exclusive-or of two arrays.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    array1 = np.array([0, 10, 20, 40, 60, 80])
    logger.debug("Array1: {}".format(array1))
    array2 = [10, 30, 40, 50, 70]
    logger.debug("Array2: {}".format(array2))
    
    # numpy.setxor1d() function find the set exclusive-or of two arrays and return the sorted, unique values that are in only one (not both) of the input arrays.
    logger.debug("Unique values that are in only one (not both) of the input arrays: {}".format(np.setxor1d(array1, array2)))

if __name__ == "__main__":
    to_find_set_exclusive_or_of_two_arrays()



2022-01-19 01:38:34,424:Logger:Array1: [ 0 10 20 40 60 80]
2022-01-19 01:38:34,425:Logger:Array2: [10, 30, 40, 50, 70]
2022-01-19 01:38:34,425:Logger:Unique values that are in only one (not both) of the input arrays: [ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.

In [18]:
from Logger import logger
import numpy as np

def to_compare_two_arrays():
    """
       Description:
          Function is used to compare two arrays.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    a = np.array([1, 2])
    b = np.array([4, 5])
    logger.debug("Array a: {}".format(a))
    logger.debug("Array b: {}".format(b))
    logger.debug("Comparison of two arrays (a > b)")
    logger.debug(np.greater(a, b))
    logger.debug("Comparison of two arrays (a >= b)")
    logger.debug(np.greater_equal(a, b))
    logger.debug("Comparison of two arrays (a < b)")
    logger.debug(np.less(a, b))
    logger.debug("Comparison of two arrays (a <= b)")
    logger.debug(np.less_equal(a, b))

if __name__ == "__main__":
    to_compare_two_arrays()

2022-01-19 01:55:17,068:Logger:Array a: [1 2]
2022-01-19 01:55:17,070:Logger:Array b: [4 5]
2022-01-19 01:55:17,072:Logger:Comparison of two arrays (a > b)
2022-01-19 01:55:17,073:Logger:[False False]
2022-01-19 01:55:17,075:Logger:Comparison of two arrays (a >= b)
2022-01-19 01:55:17,076:Logger:[False False]
2022-01-19 01:55:17,077:Logger:Comparison of two arrays (a < b)
2022-01-19 01:55:17,078:Logger:[ True  True]
2022-01-19 01:55:17,080:Logger:Comparison of two arrays (a <= b)
2022-01-19 01:55:17,080:Logger:[ True  True]


16. Write a Python program to save a NumPy array to a text file.

In [23]:
from Logger import logger
import numpy as np
import os

def to_save_a_numpy_array_text_file():
    """
       Description:
          Function is used to save a NumPy array to a text file.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    
    new_array = np.arange(12).reshape(4, 3)
    logger.debug("Original array: \n {}".format(new_array))
    header = 'col1 col2 col3'
    np.savetxt('temp.txt', new_array, fmt="%d", header=header) 
    # numpy.load() in Python is used load data from a text file, with aim to be a fast reader for simple text files.
    result = np.loadtxt('temp.txt')
    logger.debug("After loading, content of the text file:\n {}".format(result))

    
if __name__ == "__main__":
    to_save_a_numpy_array_text_file()


2022-01-19 02:10:19,110:Logger:Original array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
2022-01-19 02:10:19,116:Logger:After loading, content of the text file:
 [[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


17. Write a Python program to create a contiguous flattened array.

In [25]:
from Logger import logger
import numpy as np

def to_create_contagious_flattened_array():
    """
       Description:
          Function is used to create contagious flattened array.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    new_array = np.array([[10, 20, 30], [20, 40, 50]])
    logger.debug("Original array:\n {}".format(new_array))
    array_y = np.ravel(new_array)
    logger.debug("New flattened array:\n {}".format(array_y))
  

if __name__ == "__main__":
    to_create_contagious_flattened_array()

2022-01-19 02:19:07,886:Logger:Original array:
 [[10 20 30]
 [20 40 50]]
2022-01-19 02:19:07,888:Logger:New flattened array:
 [10 20 30 20 40 50]


18. Write a Python program to change the data type of an array.

In [29]:
from Logger import logger
import numpy as np

def to_change_data_type_of_an_array():
    """
       Description:
          Function is used to change the data type of an array.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    array1 = np.array([[2, 4, 6], [6, 8, 10]], np.int32)
    logger.debug("The Array1 is \n{}".format(array1))
    logger.debug("Data type of the array1 is:{}".format(array1.dtype))
    # Change the data type of array1
    new_array = array1.astype('float64')
    logger.debug("New Data Type of an Array is : {}".format(new_array.dtype))
    logger.debug("The New Array is \n {}".format(new_array))

if __name__ == "__main__":
    to_change_data_type_of_an_array()


2022-01-19 02:30:18,407:Logger:The Array1 is 
[[ 2  4  6]
 [ 6  8 10]]
2022-01-19 02:30:18,408:Logger:Data type of the array1 is:int32
2022-01-19 02:30:18,409:Logger:New Data Type of an Array is : float64
2022-01-19 02:30:18,410:Logger:The New Array is 
 [[ 2.  4.  6.]
 [ 6.  8. 10.]]


19.Write a Python program to create a 3-D array with ones on a diagonal and zeros elsewhere.

In [34]:
from Logger import logger
import numpy as np

def to_create_3D_array_with_ones_on_a_diagonal():
    """
       Description:
          Function is used to create 3D array with ones on a diagonal.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    new_array = np.eye(3)
    logger.debug("The aray with ones on a diagonal is \n {}".format(new_array))

if __name__ == "__main__":
   to_create_3D_array_with_ones_on_a_diagonal()

2022-01-19 02:41:20,111:Logger:The aray with ones on a diagonal is 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


20. Write a Python program to create an array which looks like below array.(lower triangular matrix)

In [38]:
from Logger import logger
import numpy as np

def to_create_array_with_lower_triangular_matrix():
    """
       Description:
          Function is used to create array with lower traingular matrix.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    new_array = np.tri(4, 3, -1)
    # numpy.tri(): Creates an array with 1’s at and below the given diagonal(about k) and 0’s elsewhere.
    logger.debug("The lower triangular matrix is \n{}".format(new_array))

if __name__ == "__main__":
    to_create_array_with_lower_triangular_matrix()


2022-01-19 03:04:23,836:Logger:The lower triangular matrix is 
[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


21. Write a Python program to concatenate two 2-dimensional arrays.

In [40]:
from Logger import logger
import numpy as np

def to_concatenate_two_2_dimentional_arrays():
    """
       Description:
          Function is used to concatenate two 2-dimentional arrays.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    array_a = np.array([[0, 1, 3], [5, 7, 9]])
    array_b = np.array([[0, 2, 4], [6, 8, 10]])
    array_c = np.concatenate((array_a, array_b), 1)
    logger.debug("The concatenated array is \n {}".format(array_c))

if __name__ == "__main__":
    to_concatenate_two_2_dimentional_arrays()


2022-01-19 03:10:37,777:Logger:The concatenated array is 
 [[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


22. Write a Python program to make an array immutable (read-only).

In [45]:
from Logger import logger
import numpy as np

def to_make_an_array_immutable():
    """
       Description:
          Function is used to make an array immutable.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
    new_array = np.zeros(10)
    new_array.flags.writeable = False
    logger.debug("Test the array is read-only or not:")
    logger.debug("Try to change the value of the first element:")
    new_array[0] = 1

if __name__ == "__main__":
    to_make_an_array_immutable()


2022-01-19 03:16:14,140:Logger:Test the array is read-only or not:
2022-01-19 03:16:14,142:Logger:Try to change the value of the first element:


ValueError: assignment destination is read-only

23.Write a Python program to create an array of (3, 4) shape, multiply every element value by 3 and display the new array.

In [46]:
from Logger import logger
import numpy as np

def to_multiply_array_element_by_any_digit():
   """
       Description:
          Function is used to  multiply array element with the digit.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
    """
   new_array= np.arange(12).reshape(3, 4)
   logger.debug("Original array elements:\n {}".format(new_array))
   for a in np.nditer(new_array, op_flags=['readwrite']):
      a[...] = 3 * a
   logger.debug("New array elements:\n {}".format(new_array))
  

if __name__ == "__main__":
   to_multiply_array_element_by_any_digit()


2022-01-19 03:24:07,633:Logger:Original array elements:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2022-01-19 03:24:07,636:Logger:New array elements:
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


24. Write a Python program to convert a NumPy array into Python list structure.


In [50]:
from Logger import logger
import numpy as np

def to_convert_numpy_array_to_python_list():
   """
       Description:
          Function is used to  convert NumPy array into Python list structure.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
   """
new_array= np.arange(6).reshape(3, 2)
logger.debug("Original array elements:\n {}".format(new_array))
logger.debug("Array to list: \n {}".format(new_array.tolist()))


if __name__ == "__main__":
    to_convert_numpy_array_to_python_list()


2022-01-19 03:31:14,776:Logger:Original array elements:
 [[0 1]
 [2 3]
 [4 5]]
2022-01-19 03:31:14,778:Logger:Array to list: 
 [[0, 1], [2, 3], [4, 5]]


25. Write a Python program to convert a NumPy array into Python list structure.

In [52]:
from Logger import logger
import numpy as np

def to_convert_numpy_array_to_python_list():
  """
       Description:
          Function is used to  convert NumPy array into Python list structure.
       Parameter:
          No parameter required.
       Return:
          Returns nothing.
   """
  new_array =np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,             
    0.35399976, 0.99469633, 0.0694458, 0.54711478]) 
  logger.debug("Original array elements:\n {}".format(new_array))
  logger.debug("Print array values with precision 3:")
  np.set_printoptions(precision=3)
  logger.debug(new_array)

if __name__ == "__main__":
  to_convert_numpy_array_to_python_list()


2022-01-19 03:37:47,391:Logger:Original array elements:
 [0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]
2022-01-19 03:37:47,393:Logger:Print array values with precision 3:
2022-01-19 03:37:47,394:Logger:[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]
